### ISSUE TITLE
Refactor bwsample into bwsample-js

### ISSUE THREAD

**Issue by ulf1** [satzbeleg/bwsample-js#1]
# TODO
- [x] setup npm package folder structure
- [x] refactor `sample` submodule
- [x] refactor `count` submodule
- [x] implement on approx p-value method in `rank` submodule
- [x] Mark EV-225 in Jira as done
